"""empty message

Revision ID: ebf81fa4b806
Revises: 
Create Date: 2021-09-29 10:21:14.823018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf81fa4b806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('dob', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('address1', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'state')
    op.drop_column('user', 'country')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
