version: '3.8'

volumes:
  loginapp3:
  appformapp3:
  schformapp3:
  frontapp3:
  
services:
  user-service:
    container_name: user
    build:
      context: ../login
    ports: 
      - "5001:5001"
    volumes:
      - loginapp3:/loginapp3
    restart: always
  
  application-service:
    container_name: application
    build:
      context: ../application_form
    ports: 
      - "5002:5002"
    volumes:
      - appformapp3:/appformapp3
    restart: always
  
  schedule-service:
    container_name: schedule
    build:
      context: ../schedule
    ports: 
      - "5003:5003"
    volumes:
      - schformapp3:/schformapp3
    restart: always
  
  frontend-service:
    container_name: frontend
    build:
      context: ../frontend
    ports: 
      - "5000:5000"
    volumes:
      - frontapp3:/frontapp3
    restart: always