version: '3.8'

volumes:
  userapp:
  applicationapp:
  scheduleapp:
  frontendapp:
  
services:
  user-service:
    container_name: user-service
    build:
      context: ../login
    ports: 
      - "5001:5001"
    volumes:
      - loginapp:/loginapp
    restart: always
  
  application-service:
    container_name: application-service
    build:
      context: ../application_form
    ports: 
      - "5002:5002"
    volumes:
      - appformapp:/appformapp
    restart: always
  
  schedule-service:
    container_name: schedule-service
    build:
      context: ../schedule
    ports: 
      - "5003:5003"
    volumes:
      - schformapp:/schformapp
    restart: always
  
  frontend-service:
    container_name: frontend-service
    build:
      context: ../frontend
    ports: 
      - "5000:5000"
    volumes:
      - frontapp:/frontapp
    restart: always