version: '3.8'

volumes:
  userapp:
  applicationapp:
  scheduleapp:
  frontendapp:
  
services:
  user-service:
    container_name: user-service-c
    build:
      context: ../login
    ports: 
      - "5001:5001"
    volumes:
      - userapp:/userapp
    restart: always
  
  application-service:
    container_name: application-service-c
    build:
      context: ../application_form
    ports: 
      - "5002:5002"
    volumes:
      - applicationapp:/applicationapp
    restart: always
  
  schedule-service:
    container_name: schedule-service-c
    build:
      context: ../schedule
    ports: 
      - "5003:5003"
    volumes:
      - scheduleapp:/scheduleapp
    restart: always
  
  frontend-service:
    container_name: frontend-service-c
    build:
      context: ../frontend
    ports: 
      - "5000:5000"
    volumes:
      - frontendapp:/frontendapp
    restart: always