"""empty message

Revision ID: 33a02be2636b
Revises: 
Create Date: 2021-09-20 17:18:28.096327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a02be2636b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('vaccination_cite', sa.String(length=255), nullable=False),
    sa.Column('first_slot', sa.DateTime(), nullable=False),
    sa.Column('second_slot', sa.DateTime(), nullable=False),
    sa.Column('medical_condition', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
