"""empty message

Revision ID: 92ae14cbb301
Revises: 
Create Date: 2021-09-20 16:37:58.808063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ae14cbb301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('indigenous_status', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=255), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=False),
    sa.Column('residence_status', sa.String(length=255), nullable=False),
    sa.Column('medicare', sa.String(length=255), nullable=False),
    sa.Column('vaccine_history', sa.String(length=255), nullable=False),
    sa.Column('work_type', sa.String(length=255), nullable=False),
    sa.Column('booker_description', sa.String(length=255), nullable=False),
    sa.Column('parking_required', sa.String(length=255), nullable=False),
    sa.Column('interpreter_required', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
